services:
  dataset_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/process/data
      - ./kaggle:/process/kaggle
    environment:
      - KAGGLE_CONFIG_DIR=/process/kaggle
    network_mode: "host"
    restart: unless-stopped
