services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    network_mode: host
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/6333'"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    depends_on:
      qdrant:
        condition: service_healthy
    network_mode: host

volumes:
  qdrant_storage:
